# 配置文件

runningMode: debug

screen:
  rX: 1024
  rY: 800
  title: Campaign
  VSync:  False

scenario:
  # 最高循环速率，以在屏幕不显示时避免高速loop导致消耗大量cpu
  # 该功能可能会使垂直同步失效
  maxRate: 60

logger:
  level: debug
  logToFile: False
  filePath: log/1.log